/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconMaterialSymbolsCheckBox: typeof import('~icons/material-symbols/check-box.jsx')['default']
}
